version: "1.0"

rules:
  enabled: true                      # 是否启用规则引擎（内置 no_todo/no_debugger/文件名等检查）
  strict_mode: false                 # true=任意 error 即判定未通过；false=仅 block_commit 规则阻断提交
  diff_only: true                    # 有变更范围时仅扫描变更行，不扫全文件
  code_quality:
    enabled: true                   # 是否启用代码质量规则组
    max_complexity: 10               # 复杂度阈值（预留，当前未实现）
    action: "block_commit"           # 违反时行为：block_commit=阻止提交，warning=警告，log=仅记录
    no_debugger: true                # 是否检查并禁止 debugger 语句

  security:
    enabled: true                    # 是否启用安全规则组
    scan_secrets: true               # 是否扫描敏感信息（预留，当前未实现）
    action: "block_commit"

  naming_convention:
    enabled: true                    # 是否启用命名规范（如文件名不含空格）
    action: "warning"

  business_logic:
    enabled: true                    # 是否启用业务逻辑规则组（预留）
    action: "block_commit"
ast:
  enabled: true                      # 是否启用 AST 切片模式（按节点切分送审，减少 token）
  preview_only: false                # true=不请求大模型，仅打印将发送的切片内容（调试用）
  # vue_include_related_blocks: true   # Vue：审 script 时带 template、审 template 时带 script（默认 true），不送 style
  # vue_related_blocks_max_lines: 60   # Vue 附带块最大行数，超出截断
# AI审查配置
# 支持通过VSCode Settings UI或此配置文件进行配置
# 优先级：VSCode Settings > 此配置文件 > 默认配置
#
# 环境变量支持：
# 1. 复制 .env.example 为 .env，填入真实值（.env 已被 .gitignore 排除）
# 2. 在下方或 VSCode 设置中用 ${变量名} 引用，推荐变量名模板：
#    AGENTREVIEW_AI_API_ENDPOINT  - API 端点（如 https://api.moonshot.cn/v1）
#    AGENTREVIEW_AI_API_KEY       - API 密钥
# 3. 优先级：系统环境变量 > .env 文件
ai_review:
  enabled: true                    # 是否启用AI审查
  api_format: "openai"            # API格式：openai（OpenAI兼容格式）或 custom（自定义格式）
  api_endpoint: "${AGENTREVIEW_AI_API_ENDPOINT}"  # 或直接写 URL；OpenAI 兼容格式会自动补全 /chat/completions
  api_key: "${AGENTREVIEW_AI_API_KEY}"            # API 密钥（支持环境变量）
  model: "${AGENTREVIEW_AI_MODEL}"                  # 模型名称（需在 .env 或设置中配置，如 kimi-k2-turbo-preview）
  timeout: 30000                   # 请求超时时间（毫秒）
  temperature: 0.2                # 温度参数（0-2），降低发散建议，提升稳定性
  max_tokens: 1500                # 最大token数（配合精简提示词，减少冗长输出）
  diff_only: true                # 仅发送变更片段给 AI（默认 true）
  run_on_save: true                    # 保存文件时自动触发复审
  run_on_save_force_review: false       # 保存时强制复审（仍受防抖/限频控制）
  run_on_save_debounce_ms: 1200         # 保存防抖时间（毫秒），多次快速保存只触发一次
  run_on_save_max_runs_per_minute: 4    # 每分钟最多执行次数，超限进入冷却队列
  run_on_save_skip_same_content: true   # 内容哈希与上次一致时跳过复审（避免重复跑）
  run_on_save_min_effective_changed_lines: 8  # 有效改动行数低于此值时视为小改动，可配合风险特征决定是否跳过（0=关闭）
  run_on_save_funnel_lint_severity: "warning"  # 保存触发时：若存在不低于此级别的 diagnostics，先跳过自动复审让用户修 Lint
  funnel_lint: true                     # 是否启用 diagnostics 漏斗：先过滤与本地诊断重复的 AI 问题
  funnel_lint_severity: "warning"       # 漏斗阈值：error=仅错误级拦截，warning=警告及以上拦截
  ignore_format_only_diff: true         # 仅格式/空白变更的 diff 不送审（跳过噪声）
  ignore_comment_only_diff: true        # 仅注释变更的 diff 不送审（跳过噪声）
  # 系统提示词 - 高置信、低打扰、短提示词版本
  system_prompt: |
    你是资深前端代码审查员。仅报告高置信、可复现、会影响功能正确性/安全性/明显性能的问题。
    不要报告样式、命名、主观偏好、证据不足的问题。
    若与已知 diagnostics/Linter 问题重复，请忽略。
    最多输出 5 条，按风险从高到低排序；无问题时返回 {"issues":[]}
    仅返回 JSON，不要附加解释文字。

    返回格式：
    {
      "issues": [
        {
          "file": "文件路径",
          "line": 行号,
          "column": 列号,
          "snippet": "原始代码片段(1-3行)",
          "message": "问题与修复建议（简洁且可操作）",
          "severity": "error|warning|info"
        }
      ]
    }
  retry_count: 3                  # API请求失败时的重试次数
  retry_delay: 1000               # 重试延迟时间（毫秒）
  action: "warning"               # 发现问题时的行为：block_commit（阻止提交）、warning（警告但允许）、log（仅记录）
runtime_log:
  enabled: false
  human_readable:
    enabled: true
    granularity: "summary_with_key_events"
    auto_generate_on_run_end: true

# 只审查以下类型的源码；未列出的文件（如 lock、min.js）自动忽略
inclusions:
  files:
    - "**/*.js"
    - "**/*.ts"
    - "**/*.jsx"
    - "**/*.tsx"
    - "**/*.vue"
    - "**/*.mjs"
    - "**/*.cjs"
    - "**/*.mts"
    - "**/*.cts"
    - "**/*.svelte"

exclusions:
  directories:
    - ".git"
    - "dist"
    - "node_modules"
